name: Build Chrome Extension

on:
  push:
    branches:
      - main  # Измените на вашу основную ветку

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Явно указываем версию Node.js 16

      - name: Log Node.js and npm versions
        run: |
          node -v
          npm -v

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build  # Замените на вашу команду сборки

      - name: Archive build files
        run: zip -r release.zip ./dist  # Архивируем папку с результатами сборки

      - name: Create or Update Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: latest  # Используем тег "latest" или настройте автоматическое увеличение версии
          files: release.zip  # Указываем файл архива
          name: Chrome Extension Release  # Название релиза
          body: |
            Автоматический релиз с последними изменениями.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Используем встроенный токен GitHub
