name: Build Electronics Project

on:
  push:
    branches:
      - main  # Замість "main" вкажіть вашу основну гілку

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get install -y <пакети>  # Встановіть необхідні пакети для вашого проекту

      - name: Build project
        run: |
          <ваша команда для збірки>  # Замените на вашу команду, наприклад, make, platformio, і т.д.

      - name: Archive build files
        run: |
          zip -r release.zip <шлях до ваших артефактів>  # Архівуйте результати зборки

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: latest  # Або використовуйте автоматичне збільшення версії
          files: release.zip  # Вказуємо файл архіву
          name: Latest Release  # Назва релізу
          body: |
            Автоматично оновлений реліз з останніми змінами в електронному проекті.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Токен для доступу до API GitHub
